# coding: utf-8

"""
    JOJ Horse

    Git version: c708a22@2022-04-29T05:03:06Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_detail_with_domain_role_list_resp import UserDetailWithDomainRoleListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserDetailWithDomainRoleListResp(unittest.TestCase):
    """UserDetailWithDomainRoleListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetailWithDomainRoleListResp(self):
        """Test UserDetailWithDomainRoleListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_detail_with_domain_role_list_resp.UserDetailWithDomainRoleListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
