# coding: utf-8

"""
    JOJ Horse

    Git version: 1654841@2022-02-19T13:17:30Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record_permission import RecordPermission  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecordPermission(unittest.TestCase):
    """RecordPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordPermission(self):
        """Test RecordPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record_permission.RecordPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
