# coding: utf-8

"""
    JOJ Horse

    Git version: 6c53391@2022-05-07T19:36:22Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_with_latest_record import ProblemWithLatestRecord  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemWithLatestRecord(unittest.TestCase):
    """ProblemWithLatestRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemWithLatestRecord(self):
        """Test ProblemWithLatestRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_with_latest_record.ProblemWithLatestRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
