# coding: utf-8

"""
    JOJ Horse

    Git version: 9384b3f@2021-07-10 18:57:18  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.api.default_api import DefaultApi  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_redirect_to_docs_get(self):
        """Test case for redirect_to_docs_get

        Redirect To Docs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
