# coding: utf-8

"""
    JOJ Horse

    Git version: e2e4bb0@2021-11-27T11:37:00Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_clone import ProblemClone  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemClone(unittest.TestCase):
    """ProblemClone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemClone(self):
        """Test ProblemClone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_clone.ProblemClone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
