# coding: utf-8

"""
    JOJ Horse

    Git version: 55b1698@2021-07-11 05:05:35  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.list_users import ListUsers  # noqa: E501
from joj.horse.client.rest import ApiException


class TestListUsers(unittest.TestCase):
    """ListUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListUsers(self):
        """Test ListUsers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.list_users.ListUsers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
