# coding: utf-8

"""
    JOJ Horse

    Git version: f24a6d9@2021-12-02T08:21:18Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.all_of_domain_user_update_role import AllOfDomainUserUpdateRole  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAllOfDomainUserUpdateRole(unittest.TestCase):
    """AllOfDomainUserUpdateRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfDomainUserUpdateRole(self):
        """Test AllOfDomainUserUpdateRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.all_of_domain_user_update_role.AllOfDomainUserUpdateRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
