# coding: utf-8

"""
    JOJ Horse

    Git version: a5c2259@2021-11-03T09:25:38Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_user_update import DomainUserUpdate  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainUserUpdate(unittest.TestCase):
    """DomainUserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserUpdate(self):
        """Test DomainUserUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_user_update.DomainUserUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
