# coding: utf-8

"""
    JOJ Horse

    Git version: 2b6cbca@2021-12-04T18:50:49Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.all_of_domain_user_add_role import AllOfDomainUserAddRole  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAllOfDomainUserAddRole(unittest.TestCase):
    """AllOfDomainUserAddRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfDomainUserAddRole(self):
        """Test AllOfDomainUserAddRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.all_of_domain_user_add_role.AllOfDomainUserAddRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
