# coding: utf-8

"""
    JOJ Horse

    Git version: 0f913fc@2021-11-30T11:39:09Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_detail_with_record_state_resp import ProblemDetailWithRecordStateResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemDetailWithRecordStateResp(unittest.TestCase):
    """ProblemDetailWithRecordStateResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemDetailWithRecordStateResp(self):
        """Test ProblemDetailWithRecordStateResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_detail_with_record_state_resp.ProblemDetailWithRecordStateResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
