# coding: utf-8

"""
    JOJ Horse

    Git version: c7442f0@2022-05-05T08:52:13Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_role_list_resp import DomainRoleListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainRoleListResp(unittest.TestCase):
    """DomainRoleListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainRoleListResp(self):
        """Test DomainRoleListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_role_list_resp.DomainRoleListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
