# coding: utf-8

"""
    JOJ Horse

    Git version: eaa141a@2022-01-17T16:33:07Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_detail_resp import DomainDetailResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainDetailResp(unittest.TestCase):
    """DomainDetailResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainDetailResp(self):
        """Test DomainDetailResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_detail_resp.DomainDetailResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
