# coding: utf-8

"""
    JOJ Horse

    Git version: 27c86c8@2021-12-12T03:59:40Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.archive_format import ArchiveFormat  # noqa: E501
from joj.horse_client.rest import ApiException


class TestArchiveFormat(unittest.TestCase):
    """ArchiveFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArchiveFormat(self):
        """Test ArchiveFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.archive_format.ArchiveFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
