# coding: utf-8

"""
    JOJ Horse

    Git version: e1ec5a4@2021-11-30T12:04:58Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.user_list import UserList  # noqa: E501
from joj.horse.client.rest import ApiException


class TestUserList(unittest.TestCase):
    """UserList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserList(self):
        """Test UserList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.user_list.UserList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
