# coding: utf-8

"""
    JOJ Horse

    Git version: 961f678@2022-05-17T03:46:15Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.file_upload import FileUpload  # noqa: E501
from joj.horse_client.rest import ApiException


class TestFileUpload(unittest.TestCase):
    """FileUpload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileUpload(self):
        """Test FileUpload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.file_upload.FileUpload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
