# coding: utf-8

"""
    JOJ Horse

    Git version: 16b8c55@2021-11-30T10:39:35Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.user_access_key import UserAccessKey  # noqa: E501
from joj.horse.client.rest import ApiException


class TestUserAccessKey(unittest.TestCase):
    """UserAccessKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAccessKey(self):
        """Test UserAccessKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.user_access_key.UserAccessKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
