# coding: utf-8

"""
    JOJ Horse

    Git version: ae9905f@2021-11-20T17:34:51Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.score import Score  # noqa: E501
from joj.horse.client.rest import ApiException


class TestScore(unittest.TestCase):
    """Score unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScore(self):
        """Test Score"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.score.Score()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
