# coding: utf-8

"""
    JOJ Horse

    Git version: e179b35@2021-12-11T14:02:24Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record import Record  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecord(self):
        """Test Record"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record.Record()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
