# coding: utf-8

"""
    JOJ Horse

    Git version: 6f1193e@2021-12-14T20:40:31Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_preview_with_record_state import ProblemPreviewWithRecordState  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemPreviewWithRecordState(unittest.TestCase):
    """ProblemPreviewWithRecordState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemPreviewWithRecordState(self):
        """Test ProblemPreviewWithRecordState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_preview_with_record_state.ProblemPreviewWithRecordState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
