# coding: utf-8

"""
    JOJ Horse

    Git version: baceace@2021-11-05T20:56:21Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_user_list import DomainUserList  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainUserList(unittest.TestCase):
    """DomainUserList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserList(self):
        """Test DomainUserList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_user_list.DomainUserList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
