# coding: utf-8

"""
    JOJ Horse

    Git version: 1a21292@2021-07-12 11:04:16  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.body_update_problem_config_api_v1_domains_domain_problems_problem_config_patch import BodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch  # noqa: E501
from joj.horse.client.rest import ApiException


class TestBodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch(unittest.TestCase):
    """BodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch(self):
        """Test BodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.body_update_problem_config_api_v1_domains_domain_problems_problem_config_patch.BodyUpdateProblemConfigApiV1DomainsDomainProblemsProblemConfigPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
