# coding: utf-8

"""
    JOJ Horse

    Git version: 36ea0f6@2021-11-15T03:52:57Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_edit import DomainEdit  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainEdit(unittest.TestCase):
    """DomainEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainEdit(self):
        """Test DomainEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_edit.DomainEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
