# coding: utf-8

"""
    JOJ Horse

    Git version: c3a0def@2022-05-10T18:12:53Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_edit import ProblemEdit  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemEdit(unittest.TestCase):
    """ProblemEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemEdit(self):
        """Test ProblemEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_edit.ProblemEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
