# coding: utf-8

"""
    JOJ Horse

    Git version: 2b6cbca@2021-12-04T18:50:49Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.jwt_access_token_resp import JWTAccessTokenResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestJWTAccessTokenResp(unittest.TestCase):
    """JWTAccessTokenResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJWTAccessTokenResp(self):
        """Test JWTAccessTokenResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.jwt_access_token_resp.JWTAccessTokenResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
