# coding: utf-8

"""
    JOJ Horse

    Git version: 307ba8d@2021-11-11T16:39:45Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_list import DomainList  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainList(unittest.TestCase):
    """DomainList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainList(self):
        """Test DomainList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_list.DomainList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
