# coding: utf-8

"""
    JOJ Horse

    Git version: b1c58ab@2023-02-02T06:47:53Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.language import Language  # noqa: E501
from joj.horse_client.rest import ApiException


class TestLanguage(unittest.TestCase):
    """Language unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguage(self):
        """Test Language"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.language.Language()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
