# coding: utf-8

"""
    JOJ Horse

    Git version: 18a8a27@2021-12-08T21:19:12Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_with_record_state_list_resp import ProblemWithRecordStateListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemWithRecordStateListResp(unittest.TestCase):
    """ProblemWithRecordStateListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemWithRecordStateListResp(self):
        """Test ProblemWithRecordStateListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_with_record_state_list_resp.ProblemWithRecordStateListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
