# coding: utf-8

"""
    JOJ Horse

    Git version: bd4013e@2022-06-02T07:35:31Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record_list_detail import RecordListDetail  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecordListDetail(unittest.TestCase):
    """RecordListDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordListDetail(self):
        """Test RecordListDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record_list_detail.RecordListDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
