# coding: utf-8

"""
    JOJ Horse

    Git version: 7bd720a@2022-02-19T13:26:22Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_tag import DomainTag  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainTag(unittest.TestCase):
    """DomainTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainTag(self):
        """Test DomainTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_tag.DomainTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
