# coding: utf-8

"""
    JOJ Horse

    Git version: 40ddcb7@2022-05-04T05:20:29Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_resp import DomainResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainResp(unittest.TestCase):
    """DomainResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainResp(self):
        """Test DomainResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_resp.DomainResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
