# coding: utf-8

"""
    JOJ Horse

    Git version: fa5e9c9@2022-01-28T15:03:21Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.auth_tokens_resp import AuthTokensResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAuthTokensResp(unittest.TestCase):
    """AuthTokensResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthTokensResp(self):
        """Test AuthTokensResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.auth_tokens_resp.AuthTokensResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
