# coding: utf-8

"""
    JOJ Horse

    Git version: c2626d3@2023-02-03T07:14:12Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record_preview import RecordPreview  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecordPreview(unittest.TestCase):
    """RecordPreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordPreview(self):
        """Test RecordPreview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record_preview.RecordPreview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
