# coding: utf-8

"""
    JOJ Horse

    Git version: fd9bd99@2022-01-03T16:37:32Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_set_add_problem import ProblemSetAddProblem  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemSetAddProblem(unittest.TestCase):
    """ProblemSetAddProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSetAddProblem(self):
        """Test ProblemSetAddProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_set_add_problem.ProblemSetAddProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
