# coding: utf-8

"""
    JOJ Horse

    Git version: 78d3530@2021-12-21T19:17:45Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.http_validation_error import HTTPValidationError  # noqa: E501
from joj.horse_client.rest import ApiException


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHTTPValidationError(self):
        """Test HTTPValidationError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.http_validation_error.HTTPValidationError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
