# coding: utf-8

"""
    JOJ Horse

    Git version: e474704@2021-06-09 05:40:56  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.any_of_problem_set_domain import AnyOfProblemSetDomain  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAnyOfProblemSetDomain(unittest.TestCase):
    """AnyOfProblemSetDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfProblemSetDomain(self):
        """Test AnyOfProblemSetDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.any_of_problem_set_domain.AnyOfProblemSetDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
