# coding: utf-8

"""
    JOJ Horse

    Git version: e3511c4@2021-07-12 17:57:12  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.config import Config  # noqa: E501
from joj.horse.client.rest import ApiException


class TestConfig(unittest.TestCase):
    """Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfig(self):
        """Test Config"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.config.Config()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
