# coding: utf-8

"""
    JOJ Horse

    Git version: 51103bd@2022-05-05T21:34:09Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_detail_with_domain_role import UserDetailWithDomainRole  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserDetailWithDomainRole(unittest.TestCase):
    """UserDetailWithDomainRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetailWithDomainRole(self):
        """Test UserDetailWithDomainRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_detail_with_domain_role.UserDetailWithDomainRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
