# coding: utf-8

"""
    JOJ Horse

    Git version: 8a4e1ee@2021-07-16 09:35:37  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_transfer import DomainTransfer  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainTransfer(unittest.TestCase):
    """DomainTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainTransfer(self):
        """Test DomainTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_transfer.DomainTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
