# coding: utf-8

"""
    JOJ Horse

    Git version: 5c38b66@2021-06-15 12:19:18  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_set import ProblemSet  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemSet(unittest.TestCase):
    """ProblemSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSet(self):
        """Test ProblemSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_set.ProblemSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
