# coding: utf-8

"""
    JOJ Horse

    Git version: 8ddb50e@2022-05-25T10:22:49Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_group_list import ProblemGroupList  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemGroupList(unittest.TestCase):
    """ProblemGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemGroupList(self):
        """Test ProblemGroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_group_list.ProblemGroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
