# coding: utf-8

"""
    JOJ Horse

    Git version: f4a351d@2022-07-06T03:30:14Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.auth_tokens_with_lakefs_resp import AuthTokensWithLakefsResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAuthTokensWithLakefsResp(unittest.TestCase):
    """AuthTokensWithLakefsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthTokensWithLakefsResp(self):
        """Test AuthTokensWithLakefsResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.auth_tokens_with_lakefs_resp.AuthTokensWithLakefsResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
