# coding: utf-8

"""
    JOJ Horse

    Git version: 3b82b34@2021-09-28 14:44:31  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.record_case import RecordCase  # noqa: E501
from joj.horse.client.rest import ApiException


class TestRecordCase(unittest.TestCase):
    """RecordCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordCase(self):
        """Test RecordCase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.record_case.RecordCase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
