# coding: utf-8

"""
    JOJ Horse

    Git version: dad896a@2021-06-08 19:53:00  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.list_problems_resp import ListProblemsResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestListProblemsResp(unittest.TestCase):
    """ListProblemsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListProblemsResp(self):
        """Test ListProblemsResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.list_problems_resp.ListProblemsResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
