# coding: utf-8

"""
    JOJ Horse

    Git version: 81180bd@2021-12-22T11:27:51Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_role_resp import DomainRoleResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainRoleResp(unittest.TestCase):
    """DomainRoleResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainRoleResp(self):
        """Test DomainRoleResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_role_resp.DomainRoleResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
