# coding: utf-8

"""
    JOJ Horse

    Git version: 3520346@2022-05-23T03:34:13Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.all_of_domain_permission_problem_set import AllOfDomainPermissionProblemSet  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAllOfDomainPermissionProblemSet(unittest.TestCase):
    """AllOfDomainPermissionProblemSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfDomainPermissionProblemSet(self):
        """Test AllOfDomainPermissionProblemSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.all_of_domain_permission_problem_set.AllOfDomainPermissionProblemSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
