# coding: utf-8

"""
    JOJ Horse

    Git version: c31343f@2022-05-12T02:05:27Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_resp import UserResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserResp(unittest.TestCase):
    """UserResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserResp(self):
        """Test UserResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_resp.UserResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
