# coding: utf-8

"""
    JOJ Horse

    Git version: 62435b4@2022-01-18T20:38:54Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_create import ProblemCreate  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemCreate(unittest.TestCase):
    """ProblemCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemCreate(self):
        """Test ProblemCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_create.ProblemCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
