# coding: utf-8

"""
    JOJ Horse

    Git version: 2b6cbca@2021-12-04T18:50:49Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.user_with_domain_role_resp import UserWithDomainRoleResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestUserWithDomainRoleResp(unittest.TestCase):
    """UserWithDomainRoleResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserWithDomainRoleResp(self):
        """Test UserWithDomainRoleResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.user_with_domain_role_resp.UserWithDomainRoleResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
