# coding: utf-8

"""
    JOJ Horse

    Git version: 55b1698@2021-07-11 05:05:35  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.list_domain_roles import ListDomainRoles  # noqa: E501
from joj.horse.client.rest import ApiException


class TestListDomainRoles(unittest.TestCase):
    """ListDomainRoles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDomainRoles(self):
        """Test ListDomainRoles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.list_domain_roles.ListDomainRoles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
