# coding: utf-8

"""
    JOJ Horse

    Git version: 4bafe89@2022-05-14T18:47:05Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.diff import Diff  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDiff(unittest.TestCase):
    """Diff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiff(self):
        """Test Diff"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.diff.Diff()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
