# coding: utf-8

"""
    JOJ Horse

    Git version: b2b50a8@2021-11-30T20:07:57Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.judge_claim_resp import JudgeClaimResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestJudgeClaimResp(unittest.TestCase):
    """JudgeClaimResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJudgeClaimResp(self):
        """Test JudgeClaimResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.judge_claim_resp.JudgeClaimResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
