# coding: utf-8

"""
    JOJ Horse

    Git version: b3dd20f@2021-12-03T09:57:48Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_user_permission import DomainUserPermission  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainUserPermission(unittest.TestCase):
    """DomainUserPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserPermission(self):
        """Test DomainUserPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_user_permission.DomainUserPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
