# coding: utf-8

"""
    JOJ Horse

    Git version: 4122cce@2021-06-19 09:55:11  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.list_problem_groups import ListProblemGroups  # noqa: E501
from joj.horse.client.rest import ApiException


class TestListProblemGroups(unittest.TestCase):
    """ListProblemGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListProblemGroups(self):
        """Test ListProblemGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.list_problem_groups.ListProblemGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
