# coding: utf-8

"""
    JOJ Horse

    Git version: aa366f6@2022-05-06T20:09:31Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_list_resp import ProblemListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemListResp(unittest.TestCase):
    """ProblemListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemListResp(self):
        """Test ProblemListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_list_resp.ProblemListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
