# coding: utf-8

"""
    JOJ Horse

    Git version: 0ae99f8@2023-02-03T06:54:51Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_edit import UserEdit  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserEdit(unittest.TestCase):
    """UserEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserEdit(self):
        """Test UserEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_edit.UserEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
