# coding: utf-8

"""
    JOJ Horse

    Git version: 55b1698@2021-07-11 05:05:35  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.all_of_problem_create_data_version import AllOfProblemCreateDataVersion  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAllOfProblemCreateDataVersion(unittest.TestCase):
    """AllOfProblemCreateDataVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfProblemCreateDataVersion(self):
        """Test AllOfProblemCreateDataVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.all_of_problem_create_data_version.AllOfProblemCreateDataVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
