# coding: utf-8

"""
    JOJ Horse

    Git version: d3f6f67@2022-05-31T04:21:08Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.config_missing import ConfigMissing  # noqa: E501
from joj.horse_client.rest import ApiException


class TestConfigMissing(unittest.TestCase):
    """ConfigMissing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigMissing(self):
        """Test ConfigMissing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.config_missing.ConfigMissing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
