# coding: utf-8

"""
    JOJ Horse

    Git version: 18a8a27@2021-12-08T21:19:12Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_detail import UserDetail  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserDetail(unittest.TestCase):
    """UserDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetail(self):
        """Test UserDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_detail.UserDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
