# coding: utf-8

"""
    JOJ Horse

    Git version: 7a3f584@2021-07-21 04:28:13  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.all_of_domain_role_create_permission import AllOfDomainRoleCreatePermission  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAllOfDomainRoleCreatePermission(unittest.TestCase):
    """AllOfDomainRoleCreatePermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfDomainRoleCreatePermission(self):
        """Test AllOfDomainRoleCreatePermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.all_of_domain_role_create_permission.AllOfDomainRoleCreatePermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
