# coding: utf-8

"""
    JOJ Horse

    Git version: c4a9464@2022-05-31T05:05:16Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.any_of_validation_error_loc_items import AnyOfValidationErrorLocItems  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAnyOfValidationErrorLocItems(unittest.TestCase):
    """AnyOfValidationErrorLocItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfValidationErrorLocItems(self):
        """Test AnyOfValidationErrorLocItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.any_of_validation_error_loc_items.AnyOfValidationErrorLocItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
