# coding: utf-8

"""
    JOJ Horse

    Git version: cdd7fda@2021-11-30T09:51:03Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_invitation_edit import DomainInvitationEdit  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainInvitationEdit(unittest.TestCase):
    """DomainInvitationEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainInvitationEdit(self):
        """Test DomainInvitationEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_invitation_edit.DomainInvitationEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
