# coding: utf-8

"""
    JOJ Horse

    Git version: c2626d3@2023-02-03T07:14:12Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.api.admin_api import AdminApi  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_admin_create_judger(self):
        """Test case for v1_admin_create_judger

        Admin Create Judger  # noqa: E501
        """
        pass

    def test_v1_admin_get_user(self):
        """Test case for v1_admin_get_user

        Admin Get User  # noqa: E501
        """
        pass

    def test_v1_admin_list_domain_roles(self):
        """Test case for v1_admin_list_domain_roles

        Admin List Domain Roles  # noqa: E501
        """
        pass

    def test_v1_admin_list_judgers(self):
        """Test case for v1_admin_list_judgers

        Admin List Judgers  # noqa: E501
        """
        pass

    def test_v1_admin_list_user_domains(self):
        """Test case for v1_admin_list_user_domains

        Admin List User Domains  # noqa: E501
        """
        pass

    def test_v1_admin_list_users(self):
        """Test case for v1_admin_list_users

        Admin List Users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
