# coding: utf-8

"""
    JOJ Horse

    Git version: 5c80f1d@2021-12-22T08:30:51Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.detail import Detail  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDetail(unittest.TestCase):
    """Detail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetail(self):
        """Test Detail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.detail.Detail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
