# coding: utf-8

"""
    JOJ Horse

    Git version: 1532c54@2021-12-05T18:56:28Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.api.record_api import RecordApi  # noqa: E501
from joj.horse.client.rest import ApiException


class TestRecordApi(unittest.TestCase):
    """RecordApi unit test stubs"""

    def setUp(self):
        self.api = RecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_record_api_v1_domains_domain_records_record_get(self):
        """Test case for get_record_api_v1_domains_domain_records_record_get

        Get Record  # noqa: E501
        """
        pass

    def test_get_record_code_api_v1_domains_domain_records_record_code_get(self):
        """Test case for get_record_code_api_v1_domains_domain_records_record_code_get

        Get Record Code  # noqa: E501
        """
        pass

    def test_list_records_in_domain_api_v1_domains_domain_records_get(self):
        """Test case for list_records_in_domain_api_v1_domains_domain_records_get

        List Records In Domain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
