# coding: utf-8

"""
    JOJ Horse

    Git version: d436ddf@2021-11-06T09:32:11Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.auth_tokens_resp import AuthTokensResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestAuthTokensResp(unittest.TestCase):
    """AuthTokensResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthTokensResp(self):
        """Test AuthTokensResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.auth_tokens_resp.AuthTokensResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
