# coding: utf-8

"""
    JOJ Horse

    Git version: cb8a591@2021-11-30T09:11:12Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.archive_format1 import ArchiveFormat1  # noqa: E501
from joj.horse.client.rest import ApiException


class TestArchiveFormat1(unittest.TestCase):
    """ArchiveFormat1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArchiveFormat1(self):
        """Test ArchiveFormat1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.archive_format1.ArchiveFormat1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
