# coding: utf-8

"""
    JOJ Horse

    Git version: 3bf3d9e@2022-01-03T17:46:04Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.judge_claim import JudgeClaim  # noqa: E501
from joj.horse_client.rest import ApiException


class TestJudgeClaim(unittest.TestCase):
    """JudgeClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJudgeClaim(self):
        """Test JudgeClaim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.judge_claim.JudgeClaim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
