# coding: utf-8

"""
    JOJ Horse

    Git version: 9384b3f@2021-07-10 18:57:18  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.score_board_resp import ScoreBoardResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestScoreBoardResp(unittest.TestCase):
    """ScoreBoardResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScoreBoardResp(self):
        """Test ScoreBoardResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.score_board_resp.ScoreBoardResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
