# coding: utf-8

"""
    JOJ Horse

    Git version: bd4013e@2022-06-02T07:35:31Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.empty_resp import EmptyResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestEmptyResp(unittest.TestCase):
    """EmptyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmptyResp(self):
        """Test EmptyResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.empty_resp.EmptyResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
