# coding: utf-8

"""
    JOJ Horse

    Git version: 6c53391@2022-05-07T19:36:22Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_set_update_problem import ProblemSetUpdateProblem  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemSetUpdateProblem(unittest.TestCase):
    """ProblemSetUpdateProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSetUpdateProblem(self):
        """Test ProblemSetUpdateProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_set_update_problem.ProblemSetUpdateProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
