# coding: utf-8

"""
    JOJ Horse

    Git version: c90a1f1@2022-05-08T15:16:12Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_set_detail import ProblemSetDetail  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemSetDetail(unittest.TestCase):
    """ProblemSetDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSetDetail(self):
        """Test ProblemSetDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_set_detail.ProblemSetDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
