# coding: utf-8

"""
    JOJ Horse

    Git version: 3bf3d9e@2022-01-03T17:46:04Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_resp import ProblemResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemResp(unittest.TestCase):
    """ProblemResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemResp(self):
        """Test ProblemResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_resp.ProblemResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
