# coding: utf-8

"""
    JOJ Horse

    Git version: fc491db@2022-05-20T21:40:10Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_config_detail_list_resp import ProblemConfigDetailListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemConfigDetailListResp(unittest.TestCase):
    """ProblemConfigDetailListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemConfigDetailListResp(self):
        """Test ProblemConfigDetailListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_config_detail_list_resp.ProblemConfigDetailListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
