# coding: utf-8

"""
    JOJ Horse

    Git version: c7442f0@2022-05-05T08:52:13Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.domain_user_update import DomainUserUpdate  # noqa: E501
from joj.horse_client.rest import ApiException


class TestDomainUserUpdate(unittest.TestCase):
    """DomainUserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserUpdate(self):
        """Test DomainUserUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.domain_user_update.DomainUserUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
