# coding: utf-8

"""
    JOJ Horse

    Git version: 9123c97@2022-05-12T03:29:47Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.user_list_resp import UserListResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestUserListResp(unittest.TestCase):
    """UserListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserListResp(self):
        """Test UserListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.user_list_resp.UserListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
