# coding: utf-8

"""
    JOJ Horse

    Git version: b52161f@2021-12-03T17:57:08Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_edit import ProblemEdit  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemEdit(unittest.TestCase):
    """ProblemEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemEdit(self):
        """Test ProblemEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_edit.ProblemEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
