# coding: utf-8

"""
    JOJ Horse

    Git version: 4e36cd1@2021-12-02T08:04:07Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.record_list_resp import RecordListResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestRecordListResp(unittest.TestCase):
    """RecordListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordListResp(self):
        """Test RecordListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.record_list_resp.RecordListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
