# coding: utf-8

"""
    JOJ Horse

    Git version: 07b808e@2022-01-16T17:39:01Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_group import ProblemGroup  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemGroup(unittest.TestCase):
    """ProblemGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemGroup(self):
        """Test ProblemGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_group.ProblemGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
