# coding: utf-8

"""
    JOJ Horse

    Git version: 229685b@2022-05-11T18:09:02Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record_state import RecordState  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecordState(unittest.TestCase):
    """RecordState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordState(self):
        """Test RecordState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record_state.RecordState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
