# coding: utf-8

"""
    JOJ Horse

    Git version: a96b428@2021-06-19 11:39:22  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_resp import ProblemResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemResp(unittest.TestCase):
    """ProblemResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemResp(self):
        """Test ProblemResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_resp.ProblemResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
