# coding: utf-8

"""
    JOJ Horse

    Git version: bfefbbd@2021-12-02T07:55:13Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_group_list_resp import ProblemGroupListResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemGroupListResp(unittest.TestCase):
    """ProblemGroupListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemGroupListResp(self):
        """Test ProblemGroupListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_group_list_resp.ProblemGroupListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
