# coding: utf-8

"""
    JOJ Horse

    Git version: b343911@2022-05-10T10:42:09Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.judger_credentials_resp import JudgerCredentialsResp  # noqa: E501
from joj.horse_client.rest import ApiException


class TestJudgerCredentialsResp(unittest.TestCase):
    """JudgerCredentialsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJudgerCredentialsResp(self):
        """Test JudgerCredentialsResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.judger_credentials_resp.JudgerCredentialsResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
