# coding: utf-8

"""
    JOJ Horse

    Git version: 1fa22ca@2021-11-05T20:09:52Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_user_list_resp import DomainUserListResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainUserListResp(unittest.TestCase):
    """DomainUserListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserListResp(self):
        """Test DomainUserListResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_user_list_resp.DomainUserListResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
