# coding: utf-8

"""
    JOJ Horse

    Git version: df076fe@2022-01-02T17:18:29Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_set_edit import ProblemSetEdit  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemSetEdit(unittest.TestCase):
    """ProblemSetEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSetEdit(self):
        """Test ProblemSetEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_set_edit.ProblemSetEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
