# coding: utf-8

"""
    JOJ Horse

    Git version: 07316f1@2022-02-19T10:40:47Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.all_of_domain_permission_problem import AllOfDomainPermissionProblem  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAllOfDomainPermissionProblem(unittest.TestCase):
    """AllOfDomainPermissionProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfDomainPermissionProblem(self):
        """Test AllOfDomainPermissionProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.all_of_domain_permission_problem.AllOfDomainPermissionProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
