# coding: utf-8

"""
    JOJ Horse

    Git version: ded693e@2022-05-18T20:23:21Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_config_json import ProblemConfigJson  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemConfigJson(unittest.TestCase):
    """ProblemConfigJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemConfigJson(self):
        """Test ProblemConfigJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_config_json.ProblemConfigJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
