# coding: utf-8

"""
    JOJ Horse

    Git version: d47939f@2021-07-12 17:53:41  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.list_records import ListRecords  # noqa: E501
from joj.horse.client.rest import ApiException


class TestListRecords(unittest.TestCase):
    """ListRecords unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListRecords(self):
        """Test ListRecords"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.list_records.ListRecords()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
