# coding: utf-8

"""
    JOJ Horse

    Git version: e13285b@2022-06-02T06:27:27Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.problem_config_detail_list import ProblemConfigDetailList  # noqa: E501
from joj.horse_client.rest import ApiException


class TestProblemConfigDetailList(unittest.TestCase):
    """ProblemConfigDetailList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemConfigDetailList(self):
        """Test ProblemConfigDetailList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.problem_config_detail_list.ProblemConfigDetailList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
