# coding: utf-8

"""
    JOJ Horse

    Git version: f65cd26@2021-06-09 05:56:00  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.problem_set_edit import ProblemSetEdit  # noqa: E501
from joj.horse.client.rest import ApiException


class TestProblemSetEdit(unittest.TestCase):
    """ProblemSetEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemSetEdit(self):
        """Test ProblemSetEdit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.problem_set_edit.ProblemSetEdit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
