# coding: utf-8

"""
    JOJ Horse

    Git version: a96b428@2021-06-19 11:39:22  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.api.record_api import RecordApi  # noqa: E501
from joj.horse.client.rest import ApiException


class TestRecordApi(unittest.TestCase):
    """RecordApi unit test stubs"""

    def setUp(self):
        self.api = RecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_record_api_v1_records_record_get(self):
        """Test case for get_record_api_v1_records_record_get

        Get Record  # noqa: E501
        """
        pass

    def test_get_record_code_api_v1_records_record_code_get(self):
        """Test case for get_record_code_api_v1_records_record_code_get

        Get Record Code  # noqa: E501
        """
        pass

    def test_http_record_api_v1_records_record_http_post(self):
        """Test case for http_record_api_v1_records_record_http_post

        Http Record  # noqa: E501
        """
        pass

    def test_http_record_cases_api_v1_records_record_cases_http_post(self):
        """Test case for http_record_cases_api_v1_records_record_cases_http_post

        Http Record Cases  # noqa: E501
        """
        pass

    def test_list_records_api_v1_records_get(self):
        """Test case for list_records_api_v1_records_get

        List Records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
