# coding: utf-8

"""
    JOJ Horse

    Git version: 8a0e301@2022-01-28T15:10:37Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.record_case import RecordCase  # noqa: E501
from joj.horse_client.rest import ApiException


class TestRecordCase(unittest.TestCase):
    """RecordCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordCase(self):
        """Test RecordCase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.record_case.RecordCase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
