# coding: utf-8

"""
    JOJ Horse

    Git version: f6a791e@2021-11-27T07:58:36Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.user_detail_resp import UserDetailResp  # noqa: E501
from joj.horse.client.rest import ApiException


class TestUserDetailResp(unittest.TestCase):
    """UserDetailResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetailResp(self):
        """Test UserDetailResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.user_detail_resp.UserDetailResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
