# coding: utf-8

"""
    JOJ Horse

    Git version: 039716b@2021-11-17T14:23:21Z  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse.client
from joj.horse.client.models.domain_create import DomainCreate  # noqa: E501
from joj.horse.client.rest import ApiException


class TestDomainCreate(unittest.TestCase):
    """DomainCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainCreate(self):
        """Test DomainCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse.client.models.domain_create.DomainCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
