# coding: utf-8

"""
    JOJ Horse

    Git version: 0ae99f8@2023-02-03T06:54:51Z  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import joj.horse_client
from joj.horse_client.models.auth_tokens_with_lakefs import AuthTokensWithLakefs  # noqa: E501
from joj.horse_client.rest import ApiException


class TestAuthTokensWithLakefs(unittest.TestCase):
    """AuthTokensWithLakefs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthTokensWithLakefs(self):
        """Test AuthTokensWithLakefs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = joj.horse_client.models.auth_tokens_with_lakefs.AuthTokensWithLakefs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
